"""
DEPARTMENT: ADMIN
Generated from Registry + Ultimate Keyword Mapping (Union of Sources)
"""

ADMIN_ROUTES = [
    "http://localhost:5173/dept/admin",
    "http://localhost:5173/admin/a-p-i-connector-hub",
    "http://localhost:5173/admin/agent-logs",
    "http://localhost:5173/admin/alert-center",
    "http://localhost:5173/admin/alert-config-page",
    "http://localhost:5173/admin/alerts-config",
    "http://localhost:5173/admin/autocoder",
    "http://localhost:5173/admin/broker-connections",
    "http://localhost:5173/admin/broker-health",
    "http://localhost:5173/admin/deployment-controller",
    "http://localhost:5173/admin/deployments",
    "http://localhost:5173/admin/environment-settings",
    "http://localhost:5173/admin/estate-visualizer",
    "http://localhost:5173/admin/event-bus",
    "http://localhost:5173/admin/event-bus-monitor",
    "http://localhost:5173/admin/executive-summary",
    "http://localhost:5173/admin/feature-flags-page",
    "http://localhost:5173/admin/features",
    "http://localhost:5173/admin/fleet",
    "http://localhost:5173/admin/gifting-optimizer",
    "http://localhost:5173/admin/graph-browser",
    "http://localhost:5173/admin/health",
    "http://localhost:5173/admin/log-viewer",
    "http://localhost:5173/admin/logs",
    "http://localhost:5173/admin/middleware",
    "http://localhost:5173/admin/middleware-pipeline",
    "http://localhost:5173/admin/monitoring",
    "http://localhost:5173/admin/operations-dashboard",
    "http://localhost:5173/admin/ops",
    "http://localhost:5173/admin/order-management",
    "http://localhost:5173/admin/portfolio-overview",
    "http://localhost:5173/admin/report-builder",
    "http://localhost:5173/admin/service-health-grid",
    "http://localhost:5173/admin/session-manager",
    "http://localhost:5173/admin/storage",
    "http://localhost:5173/admin/storage-manager",
    "http://localhost:5173/admin/succession-modeler",
    "http://localhost:5173/admin/system-health",
    "http://localhost:5173/admin/webhook-receiver",
    "http://localhost:5173/admin/workspace-manager",
    "http://localhost:5173/admin/workspaces",
]