/**
 * ==============================================================================
 * FILE: frontend2/src/widgets/AI/MorningBriefing.jsx
 * ROLE: AI Visualization Widget
 * PURPOSE: Displays a daily AI-generated market summary.
 * ==============================================================================
 */

import React, { useEffect } from "react";
import PropTypes from "prop-types";
import useBriefingStore from "../../stores/briefingStore";
import "./MorningBriefing.css";

const MorningBriefing = ({ mock = true }) => {
  const { briefing, fetchBriefing, loading, error } = useBriefingStore();

  useEffect(() => {
    fetchBriefing(mock);
  }, [mock, fetchBriefing]);

  if (loading)
    return (
      <div className="morning-briefing loading">Generating Intelligence...</div>
    );
  if (error)
    return (
      <div className="morning-briefing error">System Offline: {error}</div>
    );
  if (!briefing) return null;

  return (
    <div className="morning-briefing">
      <div className="briefing-header">
        <h3>☕ Morning Intelligence</h3>
        <span className="date">{briefing.date}</span>
      </div>

      <div className="briefing-content">
        <section className="sector outlook">
          <h4>🌍 Global Outlook</h4>
          <p>{briefing.market_outlook}</p>
          <div
            className={`sentiment-badge ${briefing.sentiment.toLowerCase()}`}
          >
            {briefing.sentiment}
          </div>
        </section>

        <div className="split-row">
          <section className="sector events">
            <h4>⏰ Key Events</h4>
            <ul>
              {briefing.key_events.map((evt, idx) => (
                <li key={idx} className={`impact-${evt.impact.toLowerCase()}`}>
                  <span className="time">{evt.time}</span>
                  <span className="event">{evt.event}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="sector alerts">
            <h4>🔔 Portfolio Alerts</h4>
            <ul>
              {briefing.portfolio_alerts.map((alert, idx) => (
                <li key={idx} className={`type-${alert.type}`}>
                  <strong>${alert.ticker}</strong>: {alert.message}
                </li>
              ))}
            </ul>
          </section>
        </div>

        <div className="quote-box">&quot;{briefing.quote_of_the_day}&quot;</div>
      </div>

      {mock && <div className="mock-timestamp">GENERATED BY GEMINI (MOCK)</div>}
    </div>
  );
};

MorningBriefing.propTypes = {
  mock: PropTypes.bool,
};

export default MorningBriefing;
