"""
web/api/__init__.py
Exports all API routers for the gateway.
"""

from . import health_api
from . import auth_api
from . import system_api
from . import agents_api
from . import dev_api
from . import debate_api
from . import departments_api
from . import master_orchestrator_api
from . import onboarding_api
from . import tasks_api
from . import dashboard_api
from . import brokerage_api
from . import strategy_api
from . import risk_api
from . import market_data_api
from . import news_api
from . import watchlist_api
from . import scanner_api
from . import homeostasis_api
from . import evolution_api
from . import identity_api
from . import compliance_api
from . import estate_api
from . import tax_api
from . import macro_api
from . import corporate_api
from . import margin_api
from . import mobile_api
from . import integrations_api
from . import advanced_risk_api
from . import advanced_orders_api
from . import ai_assistant_api
from . import ai_predictions_api
from . import analytics_api
from . import assets_api
from . import attribution_api
from . import banking_api
from . import billing_api
from . import budgeting_api
from . import calendar_api
from . import cash_api
from . import communication_api
from . import community_api
from . import credit_api
from . import crypto_api
from . import docs_api
from . import documents_api
from . import economics_api
from . import education_api
from . import email_api
from . import enterprise_api
from . import financial_planning_api
from . import fixed_income_api
from . import growth_api
from . import hedging_api
from . import incident_api
from . import institutional_api
from . import marketplace_api
from . import ml_training_api
from . import optimization_api
from . import options_api
from . import paper_trading_api
from . import payment_transfer_api
from . import philanthropy_api
from . import politics_api
from . import privacy_api
from . import public_api
from . import research_api
from . import retirement_api
from . import search_api
from . import settlement_api
from . import social_api
from . import social_trading_api
from . import spatial_api
from .admin import deployments_api
from .admin import ops_api
from .admin import workspaces_api
from . import system_telemetry_api
from . import tax_optimization_api
from . import indicators_api
from . import compliance_144a_api
from . import market
market_api = market # Alias for consistency with gateway imports
